config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :employees do
    resources :leave_managements do
      member do
        patch 'approve'
        patch 'reject'
      end
    end
    resources :bank_accounts
    get 'filter_by_department', on: :collection
    get 'sort', on: :collection

  end

  resources :leave_managements do
    collection do
      get 'pending_leaves'
    end
  end

  resources :departments
  resources :periferals
  resources :allocates
  resources :salaries do
    collection do
      post 'calculate_salary'
    end
  end
  resources :attendances do
    collection do
      post 'import'
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  include StripSpacesConcern

  belongs_to :user
  belongs_to :department
  has_many :periferals
  has_one_attached :resume
  has_one :bank_account, dependent: :destroy
  has_many :allocates
  has_many :attendance
  has_many :salaries
  has_many :leave_managements

  accepts_nested_attributes_for :bank_account
  validates_associated :bank_account

  validates :f_name, :dob, :email, :address, :contact_no, :hire_date, :department_id, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validate :dob_cannot_be_in_the_future
  validates :contact_no, uniqueness: true, numericality: { only_integer: true }, length: { minimum: 10 }

  scope :search_by_name, ->(query) { where("f_name ILIKE :query OR email ILIKE :query", query: "%#{query}%") }

  def apply_leave(start_date, end_date, leave_type)
    leaves.create(start_date: start_date, end_date: end_date, leave_type: leave_type, status: 'pending')
  end

  def remaining_leaves
    total_leaves - leaves.where(status: 'approved').sum(:duration)
  end

  def leave_history
    leaves.order(start_date: :desc)
  end

  private

  def dob_cannot_be_in_the_future
    errors.add(:dob, 'cannot be in the future') if dob.present? && dob > Date.today
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  load_and_authorize_resource

  before_action :set_employee, only: %i[show edit update destroy]

  def filter_by_department
    if params[:department_id].present?
      @set_employees = Employee.where(department_id: params[:department_id])
    else
      @set_employees = []
    end

    respond_to do |format|
      format.json { render json: @set_employees }
    end
  end

  def sort
    @employees = Employee.order(f_name: sort_direction)
    respond_to do |format|
      format.js
    end
  end

  def index
    if current_user.role == 'employee'
      current_user_email = current_user.email
      @employees = Employee.find_by(email: current_user_email)
    else
      if params[:search]
        @employees = Employee.search_by_name(params[:search])
      else
        @employees = Employee.all
      end
    end

    if params[:order_by].present?
      order_by = params[:order_by]
      order = params[:order] || 'asc'
      if order == 'asc'
        @employees = @employees.order(order_by)
      elsif order == 'desc'
        @employees = @employees.order(order_by => :desc)
      end
    end

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Employees#{@employees.count}", template: 'employees/index.html.erb', disposition: 'attachment'   # Excluding ".pdf" extension.
      end
    end

  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Employee_#{@employee.id}", template: 'employees/emp.html.erb', disposition: 'attachment'   # Excluding ".pdf" extension.
      end
    end
  end

  def new
    @employee = Employee.new
    @employee.build_bank_account
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      @employee.destroy
      flash[:notice] = 'employee deleted successfully.'
    rescue ActiveRecord::DeleteRestrictionError => e
      flash[:alert] = 'Cannot delete employee. It has associated Bank account.'
    end
    redirect_to employees_path
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:f_name, :l_name, :dob, :email, :address, :contact_no, :designation, :hire_date, :left_date, :salary, :ctc, :department_id, :resume, bank_account_attributes: %i[bank_name account_number ifsc_code])
  end

  def sort_direction
    session[:sort_direction] = session[:sort_direction] == 'asc' ? 'desc' : 'asc'
  end

end

app/helpers/employees_helper.rb
module EmployeesHelper

  def toggle_sort_order(current_order, column)
    if current_order.present? && params[:order_by] == column
      current_order == 'asc' ? 'desc' : 'asc'
    else
      'asc'
    end
  end

  # def sort_icon(column)
  #   if params[:order_by] == column && params[:order] == 'asc'
  #     content_tag(:i, nil, class: "fa fa-arrow-up")
  #   elsif params[:order_by] == column && params[:order] == 'desc'
  #     content_tag(:i, nil, class: "fa fa-arrow-down")
  #   end
  # end
end

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.id %></td>
  <td><%= link_to employee.f_name, employee %></td>
  <td><%= employee.l_name %></td>
  <td><%= employee.email %></td>
  <td><%= employee.designation %></td>
  <td><%= employee.department.try(:department_name) %></td>
  <td><%= link_to "Edit", edit_employee_path(employee.id) %></td>
  <td><%= link_to "Destroy", employee_path(employee.id),
    method: :delete,
    data: { confirm: 'Are you sure?'} %>
  </td>
  <td><%= link_to "PDF", employee_path(employee, format: :pdf) %></td>



</tr>

app/views/employees/_form.html.erb
<%= form_with model: @employee, local: true do |form| %>

  <div>
    <%= form.label "First name" %><br>
    <%= form.text_field :f_name %>
    <% @employee.errors.full_messages_for(:f_name).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label "Last name" %><br>
    <%= form.text_field :l_name %>
    <% @employee.errors.full_messages_for(:l_name).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :dob %><br>
    <%= form.date_field :dob %>
    <% @employee.errors.full_messages_for(:dob).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
    <% @employee.errors.full_messages_for(:email).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
    <% @employee.errors.full_messages_for(:address).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :contact_no %><br>
    <%= form.telephone_field :contact_no, min: 0 %>
    <% @employee.errors.full_messages_for(:contact_no).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :designation %><br>
    <%= form.text_field :designation %>
    <% @employee.errors.full_messages_for(:designation).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :hire_date %><br>
    <%= form.date_field :hire_date %>
    <% @employee.errors.full_messages_for(:hire_date).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :left_date %><br>
    <%= form.date_field :left_date %>
    <% @employee.errors.full_messages_for(:left_date).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :in_hand_salary %><br>
    <%= form.number_field :salary, min: 0 %>
    <% @employee.errors.full_messages_for(:salary).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :ctc %><br>
    <%= form.number_field :ctc, min: 0 %>
    <% @employee.errors.full_messages_for(:ctc).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.label :Department %><br>
    <%= form.collection_select(:department_id, Department.all, :id, :department_name, prompt: true) %>
    <% @employee.errors.full_messages_for(:department_id).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :resume %><br>
    <%= form.file_field :resume %>
  </div><br>

    <%= form.fields_for :bank_account do |bd| %>

      <%= bd.label :bank_name %><br>
      <%= bd.text_field :bank_name %>
      <% @employee.bank_account.errors.full_messages_for(:bank_name).each do |message| %>
        <div style="color:red"><%= message %></div>
      <% end %>
      <br>

      <%= bd.label :ifsc_code %><br>
      <%= bd.text_field :ifsc_code %>
      <% @employee.bank_account.errors.full_messages_for(:ifsc_code).each do |message| %>
        <div style="color:red"><%= message %></div>
      <% end %>
      <br>

      <%= bd.label :account_number %><br>
      <%= bd.text_field :account_number %>
      <% @employee.bank_account.errors.full_messages_for(:account_number).each do |message| %>
        <div style="color:red"><%= message %></div>
      <% end %>
      <br>
    <% end %>

  <div>
    <%= form.submit %>
  </div>

  <%= submit_tag("Reset", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
<% end %>

app/views/employees/edit.html.erb
<%= link_to "Back To Dashboard", root_path %> <br>
<%= link_to "Back", employees_path %> <br>
<h1>Edit Employee</h1>
<%= render "form", employee: @employee %>

app/views/employees/emp.html.erb
<span>Generated at: </span>
<%= Time.now%>
<hr>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg">

      <p>
        <strong>First name: </strong>
        <%= @employee.f_name %>
      </p>

      <p>
        <strong>Last name: </strong>
        <%= @employee.l_name %>
      </p>

      <p>
        <strong>DOB: </strong>
        <%= @employee.dob %>
      </p>

      <p>
        <strong>Email: </strong>
        <%= @employee.email %>
      </p>

      <p>
        <strong>Address: </strong>
        <%= @employee.address %>
      </p>

      <p>
        <strong>Contact no: </strong>
        <%= @employee.contact_no %>
      </p>

      <p>
        <strong>Designation: </strong>
        <%= @employee.designation %>
      </p>

      <p>
        <strong>Hire date: </strong>
        <%= @employee.hire_date %>
      </p>

      <p>
        <strong>Left date: </strong>
        <%= @employee.left_date %>
      </p>

      <p>
        <strong>In hand salary: </strong>
        <%= @employee.salary %>
      </p>

      <p>
        <strong>CTC: </strong>
        <%= @employee.ctc %>
      </p>

      <p>
        <strong>Department: </strong>
        <%= @employee.department.try(:department_name) %>
      </p>

      <p>
        <strong>Bank name: </strong>
        <%= @employee.bank_account.try(:bank_name) %>
      </p>

      <p>
        <strong>IFSC code: </strong>
        <%= @employee.bank_account.try(:ifsc_code) %>
      </p>

      <p>
        <strong>Account Number: </strong>
        <%= @employee.bank_account.try(:account_number) %>
      </p>
    </div>

    <div class="col-sm">
      <% if @employee.resume.attached? %>
        <%= image_tag @employee.resume, { class: 'doc_img' } %>
      <%end%>
    </div>


  </div>
</div>

app/views/employees/index.html.erb
<div class="d-flex align-items-center justify-content-center">

  <h1>Employee List</h1>
</div>

<div class="table-responsive">

  <%if current_user.role == "admin"%>
    <%= link_to "New Employee", new_employee_path %><br><br>
    <td><%= link_to "PDF",employees_path(format: :pdf) %></td>

    <%= form_tag employees_path, method: :get do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search by name or email" %>
      <%= submit_tag "Search" %>
    <% end %>

  <%end%>

  <table class="table">
    <tr>
      <th>ID</th>
      <th>
        F_Name
        <%= link_to employees_path(order_by: "f_name", order: toggle_sort_order(params[:order], "f_name")) do %>
          <% if params[:order_by] == "f_name" && params[:order] == "asc" %>
            <i class="fa fa-sort-asc"></i>
          <% else %>
            <i class="fa fa-sort-desc"></i>
          <% end %>
        <% end
        %>
      </th>
      <th>L_Name</th>
      <th>Email
      <%= link_to employees_path(order_by: "email", order: toggle_sort_order(params[:order], "email")) do %>
        <% if params[:order_by] == "email" && params[:order] == "asc" %>
          <i class="fa fa-sort-asc"></i>
        <% else %>
          <i class="fa fa-sort-desc"></i>
        <% end %>
      <% end %>
      </th>
      <th>Designation</th>
      <th>Department</th>
      <th>EDIT</th>
      <th>DELETE</th>
      <th>PDF</th>
    </tr>
    <%= render(@employees) || "There are no Employee." %>
  </table>
</div>

app/views/employees/new.html.erb
<%= link_to "Back", employees_path %> <br>
<h1>New Employee</h1>
<%= render "form", employee: @employee %>

app/views/employees/show.html.erb
<%= link_to "Back", employees_path %> <br>

<div class="container-fluid">
  <div class="row">
    <div class="col-lg">

      <p>
        <strong>First name: </strong>
        <%= @employee.f_name %>
      </p>

      <p>
        <strong>Last name: </strong>
        <%= @employee.l_name %>
      </p>

      <p>
        <strong>DOB: </strong>
        <%= @employee.dob %>
      </p>

      <p>
        <strong>Email: </strong>
        <%= @employee.email %>
      </p>

      <p>
        <strong>Address: </strong>
        <%= @employee.address %>
      </p>

      <p>
        <strong>Contact no: </strong>
        <%= @employee.contact_no %>
      </p>

      <p>
        <strong>Designation: </strong>
        <%= @employee.designation %>
      </p>

      <p>
        <strong>Hire date: </strong>
        <%= @employee.hire_date %>
      </p>

      <p>
        <strong>Left date: </strong>
        <%= @employee.left_date %>
      </p>

      <p>
        <strong>In hand salary: </strong>
        <%= @employee.salary %>
      </p>

      <p>
        <strong>CTC: </strong>
        <%= @employee.ctc %>
      </p>

      <p>
        <strong>Department: </strong>
        <%= @employee.department.try(:department_name) %>
      </p>

      <p>
        <strong>Bank name: </strong>
        <%= @employee.bank_account.try(:bank_name) %>
      </p>

      <p>
        <strong>IFSC code: </strong>
        <%= @employee.bank_account.try(:ifsc_code) %>
      </p>

      <p>
        <strong>Account Number: </strong>
        <%= @employee.bank_account.try(:account_number) %>
      </p>
    </div>

    <div class="col-sm">
      <%if @employee.resume.attached? %>
        <%= image_tag @employee.resume, { class: 'doc_img' } %>
      <%end%>
      <br> <br> <br>
      <%= link_to "Leaves", employee_leave_managements_path(@employee.id) %>
      <%= link_to "Edit", edit_employee_path(@employee.id) %>
      <%= link_to "Destroy", employee_path(@employee.id),
        method: :delete,
        data: { confirm: 'Are you sure?'}
      %>
    </div>


  </div>
</div>