config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :employees do
    resources :leave_managements do
      member do
        patch 'approve'
        patch 'reject'
      end
    end
    resources :bank_accounts
    get 'filter_by_department', on: :collection
    get 'sort', on: :collection

  end

  resources :leave_managements do
    collection do
      get 'pending_leaves'
    end
  end

  resources :departments
  resources :periferals
  resources :allocates
  resources :salaries do
    collection do
      post 'calculate_salary'
    end
  end
  resources :attendances do
    collection do
      post 'import'
    end
  end
end

app/models/leave_management.rb
class LeaveManagement < ApplicationRecord
  belongs_to :employee

  enum status: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected' }
  enum leave_type: {
       earned_leave: 'Earned Leave',
       maternity_leave: 'Maternity Leave',
     }

  validates :start_date, :end_date, :leave_type, :status, presence: true
  validate :end_date_after_start_date

  after_initialize :set_default_status, if: :new_record?

  private

  def end_date_after_start_date
    errors.add(:end_date, 'must be after start date') if end_date <= start_date
  end

  def set_default_status
    self.status ||= :pending
  end
end

app/controllers/leave_managements_controller.rb
class LeaveManagementsController < ApplicationController
  before_action :set_employee, except: [:pending_leaves]
  before_action :set_leave_management, only: [:show, :edit, :update, :destroy, :approve, :reject, :update_reason]

  def index
    @leave_managements = @employee.leave_managements
  end

  def show
  end

  def new
    @leave_management = @employee.leave_managements.new
  end

  def edit
  end

  def create
    @leave_management = @employee.leave_managements.new(leave_management_params)

    if @leave_management.save
      redirect_to employee_leave_management_path(@employee, @leave_management), notice: 'Leave management was successfully created.'
    else
      render :new
    end
  end

  def update
    if @leave_management.update(leave_management_params)
      redirect_to employee_leave_management_path(@employee, @leave_management), notice: 'Leave management was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @leave_management.destroy
    redirect_to employee_leave_managements_path(@employee), notice: 'Leave management was successfully destroyed.'
  end

  def pending_leaves
    @pending_leaves = LeaveManagement.pending
  end

  def approve
    @leave_management.update(status: :approved)
    redirect_to pending_leaves_leave_managements_path, notice: 'Leave request approved successfully.'
  end

  def reject
    @leave_management.update(status: :rejected)
    redirect_to pending_leaves_leave_managements_path, notice: 'Leave request rejected successfully.'
  end

  private
  def set_employee
    @employee = Employee.find(params[:employee_id])
  end

  def set_leave_management
    @leave_management = @employee.leave_managements.find(params[:id])
  end

  def leave_management_params
    params.require(:leave_management).permit(:leave_type, :start_date, :end_date, :status)
  end
end

app/helpers/leave_managements_helper.rb
module LeaveManagementsHelper
end

app/views/leave_managements/_form.html.erb
<%= form_with(model: [@employee, @leave_management], local: true) do |form| %>
  <% if @leave_management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leave_management.errors.count, "error") %> prohibited this leave management from being saved:</h2>

      <ul>
        <% @leave_management.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :leave_type %>
    <%= form.select :leave_type, LeaveManagement.leave_types.values %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <% if current_user.admin? %>
    <div class="field">
      <%= form.label :status %>
      <%= form.select :status, LeaveManagement.statuses.values %>
    </div>
  <% else %>
    <%= form.hidden_field :status, value: "pending" %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leave_managements/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', employee_leave_managements_path(@employee) %>

app/views/leave_managements/index.html.erb
<h1 class="text-center">All Leave Managements</h1>

<table class="table table-bordered table-striped text-center">
  <thead class="thead-dark">
    <tr>
      <th>Leave Type</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @leave_managements.each do |leave_management| %>
      <tr>
        <td><%= leave_management.leave_type %></td>
        <td><%= leave_management.start_date %></td>
        <td><%= leave_management.end_date %></td>
        <td><%= leave_management.status %></td>
        <td><%= link_to 'Show', employee_leave_management_path(@employee, leave_management), class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_employee_leave_management_path(@employee, leave_management), class: "btn btn-secondary btn-sm" %></td>
        <td><%= link_to 'Destroy', employee_leave_management_path(@employee, leave_management), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Leave Management', new_employee_leave_management_path(@employee), class: "btn btn-success" %>

app/views/leave_managements/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', employee_leave_managements_path(@employee) %>

app/views/leave_managements/pending_leaves.html.erb
<!-- app/views/leave_managements/pending_leaves.html.erb -->
<h1>Employee Leave Requests</h1>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Employee Name</th>
      <th scope="col">Leave Type</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
      <th scope="col">Reason for Rejection</th>
    </tr>
  </thead>
  <tbody>
    <% @pending_leaves.each do |leave| %>
      <tr>
        <td><%= leave.employee.f_name %></td>
        <td><%= leave.leave_type %></td>
        <td><%= leave.start_date %></td>
        <td><%= leave.end_date %></td>
        <td><%= leave.status %></td>
        <td>
          <% if leave.pending? %>
            <%= link_to 'Approve', approve_employee_leave_management_path(leave.employee, leave), method: :patch, class: 'btn btn-success' %>
            <%= link_to 'Reject', reject_employee_leave_management_path(leave.employee, leave), method: :patch, class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leave_managements/show.html.erb
<p>
  <strong>Leave Type:</strong>
  <%= @leave_management.leave_type %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @leave_management.start_date %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @leave_management.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @leave_management.status %>
</p>

<%= link_to 'Edit', edit_employee_leave_management_path(@employee, @leave_management) %> |
<%= link_to 'Back', employee_leave_managements_path(@employee) %>