config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :employees do
    resources :leave_managements do
      member do
        patch 'approve'
        patch 'reject'
      end
    end
    resources :bank_accounts
    get 'filter_by_department', on: :collection
    get 'sort', on: :collection

  end

  resources :leave_managements do
    collection do
      get 'pending_leaves'
    end
  end

  resources :departments
  resources :periferals
  resources :allocates
  resources :salaries do
    collection do
      post 'calculate_salary'
    end
  end
  resources :attendances do
    collection do
      post 'import'
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  include StripSpacesConcern

  belongs_to :employee

  validates :status, presence: true
  validates :employee_id, presence: true

  before_save :calculate_hours_worked

  def calculate_hours_worked
    return unless check_in_time && check_out_time

    self.hours_worked = (check_out_time - check_in_time) / 3600.0
    self.hours_worked = hours_worked.round(2)

    save if persisted?
    hours_worked
  end

end

app/controllers/attendances_controller.rb
require 'fileutils'
class AttendancesController < ApplicationController
  load_and_authorize_resource

  before_action :set_attendance, only: %i[show edit update destroy]
  include Pagy::Backend

  def index
    if params[:employee_id].present? && params[:start_][:month].present?
      employee_id = params[:employee_id]
      month = Date.strptime(params[:start_][:month], '%m')
      start_date = month.beginning_of_month
      end_date = month.end_of_month
      @pagy, @attendances = pagy(Attendance.where(employee_id: employee_id, check_in_time: start_date..end_date), items: 5)
    else

      if current_user.role == 'employee'
        current_user_email = current_user.email
        emp = Employee.find_by(email: current_user_email)
        @pagy, @attendances = pagy(Attendance.where(employee: emp), items: 5)
      else
        @pagy, @attendances = pagy(Attendance.all, items: 5)
      end

    end
  end

  def show
  end

  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = Attendance.new(attendance_params)

    if @attendance.save
      redirect_to attendances_path, notice: 'Attendance was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @attendance.update(attendance_params)
      redirect_to @attendance, notice: 'Attendance was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @attendance.destroy
    redirect_to attendances_url, notice: 'Attendance was successfully destroyed.'
  end

  def import
    uploaded_file = params[:attendance][:file]

    if uploaded_file.present?
      filename = SecureRandom.uuid + ".xlsx"  # Generate unique filename
      directory = Rails.root.join("public", "uploads")
      FileUtils.mkdir_p(directory) unless File.directory?(directory)  # Create directory if it doesn't exist
      filepath = File.join(directory, filename)
      File.open(filepath, 'wb') do |file|
        file.write(uploaded_file.read)
      end
      # Schedule the worker with the persistent file path
      ExcelImportWorker.perform_async(filepath.to_s)

      flash[:notice] = "Excel import job has been queued."
      redirect_to attendances_path, notice: "Data import job has been queued."
    else
      flash[:error] = "Please select a file to upload."
      render :new
    end

    sleep(5)
    # Delete uploaded file after enqueuing worker
    File.delete(filepath) if File.exist?(filepath)
  end

  private

  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  def attendance_params
    params.require(:attendance).permit(:employee_id, :status, :check_in_time, :check_out_time, :hours_worked)
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  include Pagy::Frontend
end

app/views/attendances/_attendance.html.erb
<tr>
  <td><%= attendance.employee.try(:f_name) %></td>
  <td><%= attendance.status %></td>
  <td><%= attendance.check_in_time %></td>
  <td><%= attendance.check_out_time %></td>
  <td><%= attendance.hours_worked %></td>
  <td><%= link_to "Edit", edit_attendance_path(attendance) %></td>
  <td><%= link_to "Destroy", attendance_path(attendance),
    method: :delete,
    data: { confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/attendances/_form.html.erb
<%= form_with model: @attendance, local: true do |form| %>
  <div>
    <%= form.label "Employee Name" %><br>
    <%= form.collection_select(:employee_id, Employee.all, :id, :f_name, prompt: true) %>
    <% @attendance.errors.full_messages_for(:employee_id).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div> <br>

  <div>
    <%= form.label "Status" %><br>
    <%= form.select :status, ['Absent', 'Present', 'Half-day', 'Leave']%>
    <% @attendance.errors.full_messages_for(:status).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div> <br>

  <div>
    <%= form.label "Check in time" %><br>
    <%= form.datetime_select :check_in_time %>
    <% @attendance.errors.full_messages_for(:check_in_time).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div> <br>

  <div>
    <%= form.label "Check out time" %><br>
    <%= form.datetime_select :check_out_time %>
    <% @attendance.errors.full_messages_for(:check_out_time).each do |message| %>
      <div style="color:red"><%= message %></div>
    <% end %>
  </div> <br>

  <div>
    <%= form.submit %>
    <%= submit_tag("Reset", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<%= link_to "Back To Dashboard", root_path %> <br>
<%= link_to "Back", attendances_path %> <br>
  <h1>Edit Department</h1>
<%= render "form", attendance: @attendance %>

app/views/attendances/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Attendance</h1>
</div>

<%= link_to "New Attendance", new_attendance_path %><br><br>

<%if current_user.role == "admin"%>
  <%= form_tag attendances_path, method: :get do %>
    <%= label_tag :employee_id, "Employee:" %>
    <%= select_tag :employee_id, options_for_select(Employee.all.map { |e| [e.f_name, e.id] }) %>

    <%= label_tag :month, "Month:" %>
    <%= select_month(Date.current, { prefix: 'start_', field_name: 'month' }) %>

    <%= submit_tag "Filter" %>
  <% end %>
<% end %>


<div class="table-responsive">
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
  <table class="table">
    <tr>
      <th>Employee</th>
      <th>Status</th>
      <th>Check in </th>
      <th>Check out</th>
      <th>hours_worked</th>
      <th>edit</th>
      <th>delete</th>
    </tr>
    <%= render(@attendances) || "There are no data" %>
  </table>
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

<%= button_to "Calculate Salary", calculate_salary_salaries_path, method: :post %>

app/views/attendances/new.html.erb
<%= link_to "Back", attendances_path %> <br>
<%= form_for Attendance.new, url: {action: :import}, html: {multipart: true} do |f| %>
  <%= f.file_field :file %>
  <%= f.submit "Upload" %>
<% end %>
</br>
<%= render "form", attendance: @attendance %>

app/views/attendances/show.html.erb
<%= link_to "Back", attendances_path %> <br>
<div class="table-responsive">
  <table class="table">
    <tr>
      <th>id</th>
      <th>Status</th>
      <th>Check in </th>
      <th>Check out</th>
      <th>hours_worked</th>
      <th>edit</th>
      <th>delete</th>
    </tr>
    <tr>
      <td><%= @attendance.employee.try(:f_name) %></td>
      <td><%= @attendance.status %></td>
      <td><%= @attendance.check_in_time %></td>
      <td><%= @attendance.check_out_time %></td>
      <td><%= @attendance.hours_worked %></td>
      <td><%= link_to "Edit", edit_attendance_path(@attendance) %></td>
      <td><%= link_to "Destroy", attendance_path(@attendance),
        method: :delete,
        data: { confirm: 'Are you sure?'} %>
      </td>
    </tr>