config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :employees do
    resources :leave_managements do
      member do
        patch 'approve'
        patch 'reject'
      end
    end
    resources :bank_accounts
    get 'filter_by_department', on: :collection
    get 'sort', on: :collection

  end

  resources :leave_managements do
    collection do
      get 'pending_leaves'
    end
  end

  resources :departments
  resources :periferals
  resources :allocates
  resources :salaries do
    collection do
      post 'calculate_salary'
    end
  end
  resources :attendances do
    collection do
      post 'import'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    if user.admin?
      can :manage, :all
    elsif user.employee?
      can :read, :all
      # Add more abilities for local_user if needed
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/models/allocate.rb
class Allocate < ApplicationRecord
  include StripSpacesConcern

  belongs_to :employee, optional: true
  belongs_to :department, optional: true
  belongs_to :periferal, optional: true

  validates :department_id, presence: { message: 'Department Name cannot be blank.' }
  validates :employee_id, presence: { message: 'Employee Name cannot be blank.' }
  validates :periferal_id, presence: { message: 'Periferal Name cannot be blank.' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  include StripSpacesConcern

  belongs_to :employee

  validates :status, presence: true
  validates :employee_id, presence: true

  before_save :calculate_hours_worked

  def calculate_hours_worked
    return unless check_in_time && check_out_time

    self.hours_worked = (check_out_time - check_in_time) / 3600.0
    self.hours_worked = hours_worked.round(2)

    save if persisted?
    hours_worked
  end

end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  include StripSpacesConcern

  belongs_to :employee

  validates :bank_name, presence: true
  validates :ifsc_code, presence: true
  validates :account_number, presence: true, numericality: { only_integer: true }
end

app/models/department.rb
class Department < ApplicationRecord
  include StripSpacesConcern

  has_many :allocates
  has_many :employees, dependent: :restrict_with_exception
  has_many :periferals

  validates :department_name, presence: true, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  include StripSpacesConcern

  belongs_to :user
  belongs_to :department
  has_many :periferals
  has_one_attached :resume
  has_one :bank_account, dependent: :destroy
  has_many :allocates
  has_many :attendance
  has_many :salaries
  has_many :leave_managements

  accepts_nested_attributes_for :bank_account
  validates_associated :bank_account

  validates :f_name, :dob, :email, :address, :contact_no, :hire_date, :department_id, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validate :dob_cannot_be_in_the_future
  validates :contact_no, uniqueness: true, numericality: { only_integer: true }, length: { minimum: 10 }

  scope :search_by_name, ->(query) { where("f_name ILIKE :query OR email ILIKE :query", query: "%#{query}%") }

  def apply_leave(start_date, end_date, leave_type)
    leaves.create(start_date: start_date, end_date: end_date, leave_type: leave_type, status: 'pending')
  end

  def remaining_leaves
    total_leaves - leaves.where(status: 'approved').sum(:duration)
  end

  def leave_history
    leaves.order(start_date: :desc)
  end

  private

  def dob_cannot_be_in_the_future
    errors.add(:dob, 'cannot be in the future') if dob.present? && dob > Date.today
  end

end

app/models/leave_management.rb
class LeaveManagement < ApplicationRecord
  belongs_to :employee

  enum status: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected' }
  enum leave_type: {
       earned_leave: 'Earned Leave',
       maternity_leave: 'Maternity Leave',
     }

  validates :start_date, :end_date, :leave_type, :status, presence: true
  validate :end_date_after_start_date

  after_initialize :set_default_status, if: :new_record?

  private

  def end_date_after_start_date
    errors.add(:end_date, 'must be after start date') if end_date <= start_date
  end

  def set_default_status
    self.status ||= :pending
  end
end

app/models/periferal.rb
class Periferal < ApplicationRecord
  include StripSpacesConcern

  has_many :allocates
  has_one_attached :bill

  validates :name, :purchase_date, :purchase_cost, presence: true

  before_save :calculate_warranty_end_date

  private

  def calculate_warranty_end_date
    if warranty_duration_months.present?
      self.warranty_end_date = warranty_start_date + warranty_duration_months.to_i.months
    end
  end

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles


  belongs_to :resource,
              polymorphic: true,
              optional: true


  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/salary.rb
class Salary < ApplicationRecord
  include StripSpacesConcern

  attr_accessor :hra, :allowance, :total_earning, :income_tax, :prof_tax, :total_deduction

  belongs_to :employee
end

app/models/user.rb
class User < ApplicationRecord
  has_one :employee

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # defining rolls
  enum role: %i[admin employee]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/allocates_helper.rb
module AllocatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  include Pagy::Frontend
end

app/helpers/employees_helper.rb
module EmployeesHelper

  def toggle_sort_order(current_order, column)
    if current_order.present? && params[:order_by] == column
      current_order == 'asc' ? 'desc' : 'asc'
    else
      'asc'
    end
  end

  # def sort_icon(column)
  #   if params[:order_by] == column && params[:order] == 'asc'
  #     content_tag(:i, nil, class: "fa fa-arrow-up")
  #   elsif params[:order_by] == column && params[:order] == 'desc'
  #     content_tag(:i, nil, class: "fa fa-arrow-down")
  #   end
  # end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/periferals_helper.rb
module PeriferalsHelper
  def toggle_sort_order(current_order, column)
    if current_order.present? && params[:order_by] == column
      current_order == 'asc' ? 'desc' : 'asc'
    else
      'asc'
    end
  end
end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <hr>
    <div style="display:flex; ">

      <div style="margin-right:20px;" ><%= link_to "Home", root_path %> </div>
      <% if user_signed_in? %>
        <div style="margin-right:20px;" ><%= link_to "Employee", employees_path %> </div>

        <% if current_user.role == "admin" %>
          <div style="margin-right:20px;" ><%= link_to "Department", departments_path %> </div>
        <%end%>

        <% if current_user.role == "admin" %>
          <div style="margin-right:20px;" ><%= link_to "Periferal", periferals_path %> </div>
        <%end%>

        <% if current_user.role == "admin" %>
          <div style="margin-right:20px;" ><%= link_to "Leaves", pending_leaves_leave_managements_path %> </div>
        <%end%>

        <div style="margin-right:20px;" ><%= link_to "Allocate", allocates_path %> </div>

        <div style="margin-right:20px;" ><%= link_to "Attendance", attendances_path %> </div>

        <div style="margin-right:20px;" ><%= link_to "Salary", salaries_path %> </div>

      <%end%>

      <div style="margin-left:500px;" >
        <% if user_signed_in? %>
            Signed in as <%= current_user.name %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
            <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
        <% end %>
      </div>
    </div>
     <hr>
    <div>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>
  </body>
</html>